#!/usr/bin/env python3
#
#  git-incrypt: A git remote helper to encrypt git repositories incrementally
#  Copyright (C) 2025  Robert Schiele <rschiele@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# pylint: disable=invalid-name
'''
Encrypt git branches
'''

import subprocess
import tempfile
import os
import sys
import re
import argparse
import enum
import ctypes
import math
import pygit2

plugin = ctypes.cdll.LoadLibrary(os.path.join(os.path.dirname(__file__),
                                              'incrypt-plugin.so'))
plugin.setcryptkey.argtypes = [ctypes.c_void_p]
plugin.getcryptkey.restype = ctypes.c_void_p
plugin.encryptdata.argtypes = [
    ctypes.c_void_p, ctypes.c_size_t,
    ctypes.c_void_p, ctypes.POINTER(ctypes.c_size_t)]
plugin.decryptdata.argtypes = [
    ctypes.c_void_p, ctypes.c_size_t,
    ctypes.c_void_p, ctypes.POINTER(ctypes.c_size_t)]
plugin.encryptrefname.argtypes = [ctypes.c_void_p, ctypes.c_void_p]
plugin.decryptrefname.argtypes = [ctypes.c_void_p, ctypes.c_void_p]
plugin.set_option.argtypes = [ctypes.c_char_p, ctypes.c_size_t,
                              ctypes.c_char_p]
plugin.geturl.restype = ctypes.c_char_p
plugin.getprefix.restype = ctypes.c_char_p
plugin.hashdata.argtypes = [ctypes.c_void_p, ctypes.c_size_t, ctypes.c_void_p]
plugin.hashdatahex.argtypes = [ctypes.c_void_p, ctypes.c_size_t,
                               ctypes.c_char_p]
plugin.hashdatahex.restype = ctypes.c_char_p
plugin.globalinit.argtypes = [ctypes.c_char_p, ctypes.c_char_p]
plugin.initbare.argtypes = [ctypes.c_char_p]
plugin.mktemplate.argtypes = [ctypes.c_char_p, ctypes.c_char_p,
                              ctypes.c_char_p, ctypes.c_char_p]
plugin.mktemplate.restype = ctypes.c_char_p
plugin.fetchpattern.argtypes = [ctypes.c_char]
plugin.writemeta.argtypes = [ctypes.c_char_p]
plugin.writemeta.restype = ctypes.c_char_p

if not hasattr(pygit2.enums, 'FileMode'):
    class FileMode(enum.IntFlag):
        'definitions missing in older versions of pygit2'
        # pylint: disable=c-extension-no-member disable=protected-access
        TREE = pygit2._pygit2.GIT_FILEMODE_TREE
        # pylint: disable=c-extension-no-member disable=protected-access
        BLOB = pygit2._pygit2.GIT_FILEMODE_BLOB
    pygit2.enums.FileMode = FileMode
if not hasattr(pygit2.enums, 'ObjectType'):
    class ObjectType(enum.IntEnum):
        'definitions missing in older versions of pygit2'
        # pylint: disable=c-extension-no-member disable=protected-access
        COMMIT = pygit2._pygit2.GIT_OBJ_COMMIT
        # pylint: disable=c-extension-no-member disable=protected-access
        TREE = pygit2._pygit2.GIT_OBJ_TREE
        # pylint: disable=c-extension-no-member disable=protected-access
        BLOB = pygit2._pygit2.GIT_OBJ_BLOB
        # pylint: disable=c-extension-no-member disable=protected-access
        TAG = pygit2._pygit2.GIT_OBJ_TAG
    pygit2.enums.ObjectType = ObjectType


def encryptdata(data: bytes) -> bytes:
    'encrypt raw data'
    output = ctypes.create_string_buffer(len(data) + 16)
    poutput = ctypes.c_void_p(ctypes.addressof(output))
    outlen = ctypes.c_size_t(0)
    poutlen = ctypes.pointer(outlen)
    plugin.encryptdata(data, len(data), poutput, poutlen)
    return output.raw[:poutlen.contents.value]


def decryptdata(ciphertext: bytes) -> bytes:
    'decrypt raw data'
    output = ctypes.create_string_buffer(len(ciphertext) + 16)
    poutput = ctypes.c_void_p(ctypes.addressof(output))
    outlen = ctypes.c_size_t(0)
    poutlen = ctypes.pointer(outlen)
    plugin.decryptdata(ciphertext, len(ciphertext), poutput, poutlen)
    return output.raw[:poutlen.contents.value]


def encryptrefname(ref):
    'encrypt a refname'
    output = ctypes.create_string_buffer(
        math.ceil((20 + len(ref) + 16) * 4 / 3) + 1)
    poutput = ctypes.c_void_p(ctypes.addressof(output))
    plugin.encryptrefname(ref.encode('utf-8'), poutput)
    return output.value.decode('utf-8')


def decryptrefname(ref):
    'decrypt a refname'
    output = ctypes.create_string_buffer(math.floor(len(ref) * 3 / 4) - 20 + 1)
    poutput = ctypes.c_void_p(ctypes.addressof(output))
    plugin.decryptrefname(ref.encode('utf-8'), poutput)
    return output.value.decode('utf-8')


def sha1(data):
    'sha1 hash of data'
    output = ctypes.create_string_buffer(20)
    poutput = ctypes.c_void_p(ctypes.addressof(output))
    plugin.hashdata(data, len(data), poutput)
    return output.raw[:20]


def sha1hex(data):
    'sha1 hash of data'
    output = ctypes.create_string_buffer(41)
    poutput = ctypes.c_char_p(ctypes.addressof(output))
    return plugin.hashdatahex(data, len(data), poutput).decode('utf-8')


class CryptRepo:
    'encrypted repository'
    verbosityflags = ('-q', '-q', '-v', '-vv', '-vvv')

    def __init__(self, clearname, url, init=None, forcetrust=False):
        assert clearname, 'This does not work yet outside a git repository'
        plugin.globalinit(clearname.encode('utf-8'), url.encode('utf-8'))
        if init:
            plugin.initbare(clearname.encode('utf-8'))
            template = plugin.mktemplate(
                init.name.encode('utf-8') if init.name else None,
                init.email.encode('utf-8') if init.email else None,
                init.date.encode('utf-8') if init.date else None,
                '\n\n'.join(init.m).encode('utf-8') if init.m else None)
            self.repo = pygit2.Repository('.')
            self.meta = MetaData(self.repo).init(
                init.keys, template, 'refs/heads/master')
            self.trust(force=True, sign=True)
        else:
            self.repo = pygit2.Repository('.')
            plugin.fetchpattern('_'.encode('utf-8')[0])
            self.meta = MetaData(self.repo).read()
            if forcetrust:
                self.trust(force=forcetrust)

    def _progress_for(self, what, iterable, function):
        'iterate over iterable and show progress'
        def update():
            'update progress'
            if plugin.getprogress() and total:
                nonlocal progress
                progress += 1
                sys.stderr.write(f'\rremote: {what}'
                                 f' {progress/total:.0%}'
                                 f' ({progress}/{total})')
                sys.stderr.flush()
        total = len(iterable)
        progress = -1
        for i in iterable:
            update()
            function(i)
        update()
        if plugin.getprogress() and total:
            sys.stderr.write(', done.\n')
            sys.stderr.flush()

    class RevMode(enum.Enum):
        'mode what to retrieve from _revlist'
        BLOB = enum.auto()
        PARENT = enum.auto()
        ALL = enum.auto()

    @staticmethod
    def _revlist(mode, incl, excl=None, cwd=None):
        'run rev-list'
        text = subprocess.check_output(
            ['git', 'rev-list', '--objects', '--no-object-names'] +
            (['--filter-provided-objects', '--filter=object:type=blob']
             if mode == CryptRepo.RevMode.BLOB else
             ['--topo-order', '--reverse', '--filter=tree:0']
             if mode == CryptRepo.RevMode.PARENT else
             ['--no-walk']) +
            ['--stdin'],
            cwd=cwd, text=True, input=''.join(
                [f'{x}\n' for x in incl] +
                ([f'^{x}\n' for x in excl] if excl else [])))
        return text.strip().split('\n') if text else []

    def trust(self, force=False, sign=False):
        'trust this repository'
        if force:
            trusted = True
        else:
            try:
                expectedhash = self.repo.revparse_single(
                    plugin.getprefix().decode('utf-8') +
                    'keyhash').tree['_'].read_raw().decode('utf-8')
            except KeyError:
                expectedhash = None
            if expectedhash:
                assert expectedhash == self.meta.keyhash, \
                    f'Key hash is {self.meta.keyhash}, was {expectedhash}'
                trusted = True
            else:
                trusted = self.meta.checksigs()
        assert trusted, 'Key is not trusted'
        if sign:
            self.meta.sign()
        collector = self.repo.TreeBuilder()
        collector.insert('_', self.repo.create_blob(self.meta.keyhash),
                         pygit2.enums.FileMode.BLOB)
        colid = collector.write()
        commit = self.meta.secretcommit(
                colid, [])
        self.repo.create_reference(
            plugin.getprefix().decode('utf-8') + 'keyhash', commit, force=True)

    def getrefs(self):
        'list all cleartext references'
        def decryptobject(oid):
            'decrypt an object'
            raw = decryptdata(self.repo.get(oid).read_raw())
            return self.repo.odb.write(raw[20], raw[21:])
        plugin.fetchpattern('*'.encode('utf-8')[0])
        self.meta.read()
        self.trust()
        # [ dec(crypt) , prefdec(crypt), crypt ]
        refs = [[r[0], plugin.getprefix().decode('utf-8') + '0/' + r[0],
                 self.repo.revparse_single(r[1])]
                for r in [[decryptrefname(r), r] for r in
                          filter(lambda r: len(r) >
                                 len(plugin.getprefix().decode('utf-8'))+3 and
                                 r.startswith(plugin.getprefix().
                                              decode('utf-8') + '1/'),
                                 self.repo.references)]]
        cryptmap = self.meta.readmap(reverse=True)
        self._progress_for(
            'Decrypting objects',
            CryptRepo._revlist(CryptRepo.RevMode.BLOB, [r[2].id for r in refs],
                               cryptmap, cwd=self.repo.path),
            decryptobject)
        for r in refs:
            self.repo.create_reference(
                r[1], decryptdata(r[2].tree['0'].read_raw())[0:20].hex(), force=True)
        expected = [r[1] for r in refs]
        result = [['HEAD', f'@{self.meta.defaultbranch}']]
        for r in self.repo.references:
            if r.startswith(plugin.getprefix().decode('utf-8') + '0/'):
                if r in expected:
                    result.append(
                        [r[len(plugin.getprefix().decode('utf-8'))+2:],
                            self.repo.lookup_reference(r).target])
                else:
                    self.repo.references.delete(r)
        return result

    def push(self, refs):
        'push refs'
        def encryptobject(oid):
            'encrypt an object'
            clear = self.repo.get(oid)
            cryptobjs[clear.id] = self.repo.create_blob(encryptdata(
                clear.id.raw + clear.type.to_bytes(1, byteorder='big') +
                clear.read_raw()))

        def createcommit(oid):
            'create a commit'
            def collectorinsert(collector, oid):
                'insert an object into the collector'
                collector.insert(str(oid), oid, pygit2.enums.FileMode.BLOB)

            def encrypttree(tree):
                'encrypt a tree'
                for obj in tree:
                    if obj.type == pygit2.enums.ObjectType.TREE:
                        encrypttree(obj)
                    elif obj.type == pygit2.enums.ObjectType.BLOB:
                        collectorinsert(collector, cryptobjs[obj.id])
                collectorinsert(collector, cryptobjs[tree.id])

            obj = self.repo.get(oid)
            collector = self.repo.TreeBuilder()
            if obj.type == pygit2.enums.ObjectType.COMMIT:
                encrypttree(obj.tree)
            elif obj.type != pygit2.enums.ObjectType.TAG:
                raise TypeError(
                    f'Unexpected type {obj.type_str} in git history')
            collector.insert('0', cryptobjs[obj.id],
                             pygit2.enums.FileMode.BLOB)
            colid = collector.write()
            cryptmap[str(obj.id)] = self.meta.secretcommit(
                colid, [cryptmap[str(c)] for c in obj.parent_ids]
                if obj.type == pygit2.enums.ObjectType.COMMIT
                else [cryptmap[str(obj.target)]])

        xrefs = [[r[0], r[1], r[3], ('+' if r[2] else '') +
                  (plugin.getprefix().decode('utf-8') + '1/' +
                   r[3] if r[0] else '') +
                  ':refs/heads/' + r[3],
                  self.repo.revparse_single(r[0]) if r[0] else None]
                 for r in [[r[0], r[1], r[2],
                            encryptrefname(r[1])]
                           for r in refs]]
        cryptmap = self.meta.readmap()
        colobjs = CryptRepo._revlist(
            CryptRepo.RevMode.PARENT, [r[4].id for r in xrefs if r[4]],
            cryptmap)
        cryptobjs = {}
        self._progress_for('Encrypting objects',
                           CryptRepo._revlist(CryptRepo.RevMode.ALL, colobjs),
                           encryptobject)
        self._progress_for('Creating encrypted commits', colobjs, createcommit)
        self.meta.write(cryptmap)
        for r in xrefs:
            if r[4]:
                self.repo.create_reference(
                    plugin.getprefix().decode('utf-8') + '1/' + r[2],
                    cryptmap[str(r[4].id)], force=True)
            else:
                try:
                    self.repo.references.delete(
                        plugin.getprefix().decode('utf-8') + '1/' + r[2])
                except KeyError:
                    pass
        resdict = {}
        for line in subprocess.run(
                ['git', 'push'] +
                ([CryptRepo.verbosityflags[plugin.getverbosity()]]
                 if plugin.getverbosity() > 1 else []) +
                ['--progress' if plugin.getprogress()
                    else '--no-progress', '--porcelain'] +
                (['--atomic'] if plugin.getatomic() else []) +
                [plugin.geturl().decode('utf-8'), '+' +
                 plugin.getprefix().decode('utf-8') + '1/_:' +
                 MetaData.REFNAME] +
                [r[3] for r in xrefs],
                cwd=self.repo.path, check=False, text=True,
                stdout=subprocess.PIPE,
                stderr=sys.stderr if plugin.getverbosity() > 1
                else subprocess.DEVNULL
                ).stdout.split('\n'):
            e = line.split('\t', 2)
            if len(e) == 3:
                resdict[e[1].split(':', 1)[1]] = \
                    e[2].split('(', 1)[1][0:-1] if e[0] == '!' else None
        return {r[1]: resdict['refs/heads/' + r[2]] for r in xrefs}


def remotehelperloop():
    'communication loop'
    def fetchcommand(line):
        'parse fetch batch'
        while line:
            command = line.split()
            assert command[0] == 'fetch', \
                f'Unexpected command in fetch batch: {line}'
            line = sys.stdin.readline().strip()
        sys.stdout.write('\n')

    def pushcommand(line):
        'parse push batch'
        refs = []
        while line:
            command = line.split()
            assert command[0] == 'push', \
                f'Unexpected command in push batch: {line}'
            src, dst = command[1].split(':')
            force = len(src) and src[0] == '+'
            if force:
                src = src[1:]
            refs.append([src, dst, force])
            line = sys.stdin.readline().strip()
        results = crypt.push(refs)
        sys.stdout.write('{}\n'.format(
            ''.join([(f'error {r} {e}\n' if e else f'ok {r}\n')
                     for r, e in results.items()])))

    crypt = CryptRepo(os.environ.pop('GIT_DIR', None), sys.argv[2])
    while True:
        sys.stdout.flush()
        line = sys.stdin.readline().strip()
        if not line:
            break
        command = line.split()
        if command[0] == 'capabilities':
            sys.stdout.write('fetch\npush\noption\n\n')
        elif command[0] == 'list':
            sys.stdout.write('{}\n'.format(
                ''.join([f'{r[1]} {r[0]}\n' for r in crypt.getrefs()])))
        elif command[0] == 'fetch':
            fetchcommand(line)
        elif command[0] == 'push':
            pushcommand(line)
        elif command[0] == 'option':
            if plugin.set_option(command[1].encode('utf-8'),
                                 len(command[1].encode('utf-8')),
                                 command[2].encode('utf-8')):
                sys.stdout.write('ok\n')
            else:
                sys.stdout.write('unsupported\n')
        else:
            raise RuntimeError(f'Unknown command: {line}')


class MetaData:
    # pylint: disable=too-many-instance-attributes
    'container for meta data'
    VER = b'git-incrypt\n1.0.0\n'
    KEYVER = b'AES-256-CBC+IV'
    REFNAME = 'refs/heads/_'

    def __init__(self, repo):
        self.repo = repo
        self.files = None
        self.key = None
        self.keyhash = None
        self.template = None
        self.defaultbranch = None
        self.gpgkeys = []

    def _gpg(self, args, inp):
        'run gpg'
        return subprocess.check_output(
                [f'gpg@incrypt::{plugin.geturl().decode("utf-8")}'] + args,
                executable='gpg', input=inp)

    def init(self, gpgkeys, template, defaultbranch):
        'initialize the metadata'
        self.files = {}
        plugin.metainit()
        output = ctypes.create_string_buffer(41)
        poutput = ctypes.c_char_p(ctypes.addressof(output))
        plugin.writemeta(poutput)
        blubs = self.repo.get(output.value.decode('utf-8')).id
        self.files['ver'] = self.repo.create_blob(MetaData.VER)
        self.key = ctypes.string_at(plugin.getcryptkey(), 48) # os.urandom(48)
        keyhashbase = MetaData.KEYVER + b'\x00' + self.key
        self.keyhash = sha1hex(keyhashbase)
        cryptedkey = self._gpg(
            ['-q', '-e'] + ['-r' + k for k in gpgkeys], keyhashbase)
        self.files['key'] = self.repo.create_blob(cryptedkey)
        self.files['sig'] = self.repo.TreeBuilder().write()
        self.template = template
        self.files['msg'] = self.repo.create_blob(encryptdata(
            sha1(template) + template))
        self.defaultbranch = defaultbranch
        encodedbranch = defaultbranch.encode('utf-8')
        self.files['def'] = self.repo.create_blob(encryptdata(
            sha1(encodedbranch) + encodedbranch))
        # self.write()
        commit = self.secretcommit(blubs, [])
        self.repo.create_reference(
            plugin.getprefix().decode('utf-8') + '1/_', commit, force=True)
        return self

    def addkey(self, gpgkeys):
        'add gpg key'
        self.gpgkeys += gpgkeys
        cryptedkey = self._gpg(
            ['-q', '-e'] + ['-r' + k for k in self.gpgkeys],
            MetaData.KEYVER + b'\x00' + self.key)
        self.files['key'] = self.repo.create_blob(cryptedkey)

    def read(self):
        'read the metadata'
        self.files = {}
        tree = self.repo.revparse_single(
            plugin.getprefix().decode('utf-8') + '1/_').tree
        obj = tree['ver']
        self.files['ver'] = obj.id
        data = obj.read_raw()
        assert data == MetaData.VER, \
            f'Version format is {data}, expected {MetaData.VER}'
        obj = tree['key']
        self.files['key'] = obj.id
        data = self._gpg(['-q', '-d'], obj.read_raw())
        newkeyhash = sha1hex(data)
        if self.keyhash:
            assert newkeyhash == self.keyhash, \
                f'Key hash is {newkeyhash}, was {self.keyhash}'
        self.keyhash = newkeyhash
        keyver, self.key = data.split(b'\x00', 1)
        plugin.setcryptkey(self.key)
        assert keyver == MetaData.KEYVER, \
            f'Key format is {keyver}, expected {MetaData.KEYVER}'
        keydata = self._gpg(['-q', '--list-packets'],
                            obj.read_raw()).decode('utf-8').split('\n')
        for k in keydata:
            match = re.search(r'^:pubkey enc packet:.*keyid ([0-9A-F]+)', k)
            if match:
                self.gpgkeys.append(match.group(1))
        self.files['sig'] = tree['sig'].id
        obj = tree['msg']
        self.files['msg'] = obj.id
        data = decryptdata(obj.read_raw())
        assert sha1(data[20:]) == data[0:20], 'corrupted template'
        self.template = data[20:]
        obj = tree['def']
        self.files['def'] = obj.id
        data = decryptdata(obj.read_raw())
        assert sha1(data[20:]) == data[0:20], \
            'corrupted default branch information'
        self.defaultbranch = data[20:].decode('utf-8')
        return self

    def sign(self):
        'sign key'
        sig = self._gpg(['-q', '-b', '-s'], self.key)
        sigfile = self.repo.create_blob(encryptdata(sha1(sig) + sig))
        sigtree = self.repo.TreeBuilder(self.repo.get(self.files['sig']))
        sigtree.insert(str(sigfile), sigfile, pygit2.enums.FileMode.BLOB)
        self.files['sig'] = sigtree.write()

    def checksigs(self):
        'check signatures'
        trusted = False
        for sig in self.repo.get(self.files['sig']):
            decrypted = decryptdata(sig.read_raw())
            assert sha1(decrypted[20:]) == decrypted[0:20], \
                'corrupted signature'
            with tempfile.NamedTemporaryFile(delete=False) as tmp:
                tmp.write(decrypted[20:])
                tmp.flush()
                sigfile = tmp.name
            try:
                sigoutput = self._gpg(
                    ['--verify', '--status-fd', '1', sigfile, '-'], self.key
                    ).decode('utf-8').strip().split('\n')
                sigresults = [d.split()[1] for d in sigoutput]
                if 'GOODSIG' in sigresults and \
                        ('TRUST_ULTIMATE' in sigresults or
                         'TRUST_FULLY' in sigresults):
                    trusted = True
            finally:
                os.remove(sigfile)
        return trusted

    def secretcommit(self, tree, parents):
        'create secret commit wrapper'
        raw = b'tree ' + str(tree).encode('utf-8') + b'\n'
        for parent in parents:
            raw += b'parent ' + str(parent).encode('utf-8') + b'\n'
        raw += self.template
        return str(self.repo.odb.write(pygit2.enums.ObjectType.COMMIT, raw))

    def write(self, cryptmap=None):
        'write the metadata'
        collector = self.repo.TreeBuilder()
        for name, file in self.files.items():
            collector.insert(name, file, pygit2.enums.FileMode.TREE
                             if name == 'sig' else pygit2.enums.FileMode.BLOB)
        if not cryptmap:
            cryptmap = {}
        rawdata = b''
        for a, b in cryptmap.items():
            rawdata += bytes.fromhex(a) + bytes.fromhex(b)
        mapfile = self.repo.create_blob(encryptdata(sha1(rawdata) + rawdata))
        collector.insert('map', mapfile, pygit2.enums.FileMode.BLOB)
        readmefile = self.repo.create_blob(
            ctypes.c_char_p.in_dll(plugin, 'CRYPTREADME').value)
        collector.insert('README.md', readmefile, pygit2.enums.FileMode.BLOB)
        colid = collector.write()
        commit = self.secretcommit(colid, [])
        self.repo.create_reference(
            plugin.getprefix().decode('utf-8') + '1/_', commit, force=True)
        return self

    def readmap(self, reverse=False):
        'read the mapping table'
        tree = self.repo.revparse_single(
            plugin.getprefix().decode('utf-8') + '1/_').tree
        o = 20 if reverse else 0
        processed = {}
        rawdata = decryptdata(tree['map'].read_raw())
        for i in range(20, len(rawdata), 40):
            target = rawdata[i+20-o:i+40-o].hex()
            if target in self.repo:
                processed[rawdata[i+o:i+20+o].hex()] = target
        return processed


def init_command(args):
    'init incrypt repository'
    assert args.url.startswith('incrypt::'), \
        'url must start with incrypt::'
    with tempfile.TemporaryDirectory() as tempdir:
        crypt = CryptRepo(tempdir, args.url[9:], init=args)
        crypt.push([])


def addkey_command(args):
    'add key to incrypt repository'
    try:
        url = pygit2.Repository('.').remotes[args.remote].url
    except (KeyError, ValueError):
        url = args.remote
    assert url.startswith('incrypt::'), \
        f'url `{url}` must start with incrypt::'
    crypt = CryptRepo('.', url[9:])
    crypt.meta.addkey(args.keys)
    crypt.push([])


def trust_command(args):
    'trust incrypt repository'
    try:
        url = pygit2.Repository('.').remotes[args.remote].url
    except (KeyError, ValueError):
        url = args.remote
    assert url.startswith('incrypt::'), \
        f'url `{url}` must start with incrypt::'
    crypt = CryptRepo('.', url[9:], forcetrust=True)
    if args.sign:
        crypt.meta.sign()
        crypt.push([])


def tool():
    'git incrypt tool implementation'
    parser = argparse.ArgumentParser(
        description='git inccrypt: '
        'A git remote helper to encrypt git repositories incrementally.')
    subparsers = parser.add_subparsers(
        title='subcommands', dest='command', help='Available commands')
    subparsers.required = True
    init_parser = subparsers.add_parser(
        'init', help='Initialize the project')
    init_parser.add_argument(
        '-n', '--name', type=str, default=None,
        help='Name of the author of the encrypted commits')
    init_parser.add_argument(
        '-e', '--email', type=str, default=None,
        help='Email of the author of the encrypted commits')
    init_parser.add_argument(
        '-d', '--date', type=str, default=None,
        help='Seconds since the epoch when the encypted commits are authored')
    init_parser.add_argument(
        '-m', action='append', type=str, default=[],
        help='Message in encrypted commits')
    init_parser.add_argument(
        'url', type=str, help='URL of the remote repository')
    init_parser.add_argument(
        'keys', nargs='+', help='GPG keys used to encrypt the data')
    init_parser.set_defaults(func=init_command)
    addkey_parser = subparsers.add_parser(
        'addkey', help='Add an encryption key')
    addkey_parser.add_argument(
        'remote', type=str, help='Name of the remote')
    addkey_parser.add_argument(
        'keys', nargs='+', help='GPG keys to add')
    addkey_parser.set_defaults(func=addkey_command)
    trust_parser = subparsers.add_parser(
        'trust', help='Trust the remote repository')
    trust_parser.add_argument(
        'remote', nargs='?', default='origin',
        help='Name of the remote')
    trust_parser.add_argument(
        '-s', '--sign', action='store_true',
        help='Sign the key')
    trust_parser.set_defaults(func=trust_command)
    args = parser.parse_args()
    args.func(args)


cmd = sys.argv[0].rsplit('/', 1)[-1]

if cmd == 'git-remote-incrypt':
    remotehelperloop()
elif cmd == 'git-incrypt':
    tool()

# vim: set expandtab shiftwidth=4 tabstop=4 :
