name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoc python3-pygit2 python3-pip
      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install pylint pycodestyle
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test
        run: |
          git config --global user.email "testuser@example.com"
          git config --global user.name "Test User"
          gpg --batch --gen-key .github/workflows/testkey.conf
          make KEY:=$(gpg --list-keys --with-colons | awk -F: '/^pub/ {print $5; exit}') test
