name: Test
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-13, macos-14, macos-15]
    steps:
      - name: Install system packages (Ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoc python3-pygit2 python3-pip
      - name: Install system packages (MacOS)
        if: startsWith(matrix.os, 'macos')
        run : |
          brew update
          brew install asciidoc xmlto libgit2
          echo "XML_CATALOG_FILES=/opt/homebrew/etc/xml/catalog" >> $GITHUB_ENV
      - name: Install Python packages
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          python3 -m pip install pylint pycodestyle pygit2
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Test
        run: |
          git config --global user.email "testuser@example.com"
          git config --global user.name "Test User"
          gpg --batch --gen-key .github/workflows/testkey.conf
          source venv/bin/activate
          make KEY:=$(gpg --list-keys --with-colons | awk -F: '/^pub/ {print $5; exit}') test
